### PR TITLE
fixed some compatability issues

### PR DESCRIPTION
**Pull request by axtloss**
Made script automatically run with "su" when neither sudo, nor doas are available
Made an install script for both bsd and linux, with proper path's for the binary
Some README updates

### CODE REVIEW

**Comment by mchalunderscore** [comment]
some commits are redundant, the standard install already runs on *BSD systems, and it would be generally unwise to copy it to /usr/bin instead of /usr/local/bin
the "su" option also seems to fail during my testing
because of this, commits f1a46b6, 3eec55d, d9ebb63 and 0fb6f83 are rather redundant
consider removing them

everything else is good to merge

**Comment by axtloss** [comment]
I did the extra *BSD script because I wasn't aware that Linux systems have a /usr/local/bin, but I'm confused why the su method isn't working for you

**Comment by mchalunderscore** [comment]
```
[jnats@fedora-desktop]~/nofetch% su - root "cp nofetch /usr/local/bin" 
Password: 
-zsh: can't open input file: cp nofetch /usr/local/bin
[jnats@fedora-desktop]~/nofetch% 
```

seems to be an error w/ the syntax

**Comment by axtloss** [comment]
That's weird, for some reason it doesn't work for me too anymore, I'll remove it for now and make a pull request again once it properly works

**Comment by axtloss** [comment]
Redundant commits are now removed

**Comment by mchalunderscore** [comment]
relevant commits cherry-picked into main

**Pull request closed without merging**
